"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-q0gk&^e(i$px)+2z08h0))0%rmwq0u+59$8ieu&#r^#-wvn*&7',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]

# Sin esto, Django manda las cookies de sesión/CSRF también por HTTP plano
# (su default es False, pensado para poder arrancar en local sin HTTPS).
# En producción (DEBUG=False) siempre se sirve por HTTPS, así que se puede
# exigir aquí sin romper el entorno local (DEBUG=True en .env de desarrollo).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'paneles_gestionalda'),
        'USER': os.environ.get('DB_USER', 'paneles_app'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    },
    # Read-only connection to the Odoo PMS database (source of truth for hotel
    # operations: rooms, reservations, room blocks). Never migrate/write here.
    'odoo': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('ODOO_DB_NAME', 'odoo'),
        'USER': os.environ.get('ODOO_DB_USER', ''),
        'PASSWORD': os.environ.get('ODOO_DB_PASSWORD', ''),
        'HOST': os.environ.get('ODOO_DB_HOST', ''),
        'PORT': os.environ.get('ODOO_DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'sslmode': os.environ.get('ODOO_DB_SSLMODE', 'require'),
            'options': '-c client_encoding=UTF8',
        },
        # Nunca crear/migrar una base de test contra la producción de Odoo.
        'TEST': {'MIRROR': 'default'},
    },
}

# 'odoo' has no Django models of its own (unmanaged raw SQL access to a
# third-party schema) — keep migrations off it and never route writes there.
DATABASE_ROUTERS = ['core.db_routers.OdooReadOnlyRouter']

# Ruta a la credencial JSON de la cuenta de servicio de Google usada por
# `manage.py importar_presupuesto_fb` (ver ese comando para el porqué) — la
# cuenta de servicio necesita acceso de "Lector" a la hoja de Finanzas,
# compartido desde Google Sheets, no desde aquí. None (sin configurar) en
# local: el comando falla con un mensaje explícito en vez de un traceback.
GOOGLE_SHEETS_CREDENTIALS_FILE = os.environ.get('GOOGLE_SHEETS_CREDENTIALS_FILE') or None

# Cache en disco (no LocMemCache): gunicorn corre con varios workers, cada
# uno con su propia memoria, así que una cache en RAM del proceso solo
# acierta 1 de cada N veces. Un directorio compartido en disco lo arregla
# sin añadir Redis/Memcached — ver core/cache.py.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'django_cache',
    }
}

# Bug real encontrado 2026-09-02: un test que llama a una función real
# decorada con @cache_result (con las dependencias mockeadas, pero la
# función y su caché SIN mockear) con una fecha_inicio/fecha_fin que
# coincide con una consultada de verdad en producción, escribe el
# resultado FALSO del test en la misma caché de disco que usa gunicorn —
# quedó ahí hasta que se vació a mano, sirviendo presupuesto de un hotel
# inventado a usuarios reales durante ese rato. `cache.clear()` en
# setUp() (ver hoteles/tests.py) protege al test de caché vieja, pero no
# protege a producción de la caché que el test ACABA de escribir. Con
# 'test' en sys.argv, manage.py test usa una caché en memoria propia del
# proceso, nunca el fichero compartido.
if 'test' in sys.argv:
    CACHES['default'] = {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
