/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendenciasRouteImport } from './routes/tendencias'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelesIndexRouteImport } from './routes/hoteles.index'
import { Route as HotelesHotelIdRouteImport } from './routes/hoteles.$hotelId'

const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelesIndexRoute = HotelesIndexRouteImport.update({
  id: '/hoteles/',
  path: '/hoteles/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelesHotelIdRoute = HotelesHotelIdRouteImport.update({
  id: '/hoteles/$hotelId',
  path: '/hoteles/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/alertas': typeof AlertasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/tendencias': typeof TendenciasRoute
  '/hoteles/$hotelId': typeof HotelesHotelIdRoute
  '/hoteles/': typeof HotelesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/alertas': typeof AlertasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/tendencias': typeof TendenciasRoute
  '/hoteles/$hotelId': typeof HotelesHotelIdRoute
  '/hoteles': typeof HotelesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/alertas': typeof AlertasRoute
  '/oportunidades': typeof OportunidadesRoute
  '/tendencias': typeof TendenciasRoute
  '/hoteles/$hotelId': typeof HotelesHotelIdRoute
  '/hoteles/': typeof HotelesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/alertas'
    | '/oportunidades'
    | '/tendencias'
    | '/hoteles/$hotelId'
    | '/hoteles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/alertas'
    | '/oportunidades'
    | '/tendencias'
    | '/hoteles/$hotelId'
    | '/hoteles'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/alertas'
    | '/oportunidades'
    | '/tendencias'
    | '/hoteles/$hotelId'
    | '/hoteles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AlertasRoute: typeof AlertasRoute
  OportunidadesRoute: typeof OportunidadesRoute
  TendenciasRoute: typeof TendenciasRoute
  HotelesHotelIdRoute: typeof HotelesHotelIdRoute
  HotelesIndexRoute: typeof HotelesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteles/': {
      id: '/hoteles/'
      path: '/hoteles'
      fullPath: '/hoteles/'
      preLoaderRoute: typeof HotelesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteles/$hotelId': {
      id: '/hoteles/$hotelId'
      path: '/hoteles/$hotelId'
      fullPath: '/hoteles/$hotelId'
      preLoaderRoute: typeof HotelesHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AlertasRoute: AlertasRoute,
  OportunidadesRoute: OportunidadesRoute,
  TendenciasRoute: TendenciasRoute,
  HotelesHotelIdRoute: HotelesHotelIdRoute,
  HotelesIndexRoute: HotelesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
