# Generated by Django 5.2.17 on 2026-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_bloqueos', 'Puede ver el dashboard: Bloqueos'), ('ver_donde_actuar', 'Puede ver el dashboard: ¿Dónde actuar hoy?'), ('ver_oportunidades', 'Puede ver el dashboard: Oportunidades'), ('ver_hoteles', 'Puede ver el dashboard: Hoteles'), ('ver_tendencias', 'Puede ver el dashboard: Tendencias'), ('ver_alertas', 'Puede ver el dashboard: Alertas'), ('ver_ajustes', 'Puede ver el dashboard: Ajustes')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
