# Generated by Django 5.2.17 on 2026-08-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_bloqueos', 'Puede ver el dashboard: Bloqueos'), ('ver_donde_actuar', 'Puede ver el dashboard: ¿Dónde actuar hoy?'), ('ver_oportunidades', 'Puede ver el dashboard: Oportunidades'), ('ver_hoteles', 'Puede ver el dashboard: Hoteles'), ('ver_desayunos', 'Puede ver el dashboard: Desayunos'), ('ver_tendencias', 'Puede ver el dashboard: Tendencias'), ('ver_alertas', 'Puede ver el dashboard: Alertas'), ('ver_ajustes', 'Puede ver el dashboard: Ajustes')]},
        ),
    ]
