# Generated by Django 5.2.17 on 2026-08-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puesto_trabajo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
