# Generated by Django 5.2.17 on 2026-08-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_perfilusuario_puesto_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoRolPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_trabajo', models.CharField(max_length=200, unique=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group')),
            ],
            options={
                'verbose_name': 'Mapeo puesto → rol',
                'verbose_name_plural': 'Mapeos puesto → rol',
            },
        ),
        migrations.DeleteModel(
            name='MapeoRolDepartamento',
        ),
    ]
