# Generated by Django 5.2.17 on 2026-08-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dashboardaccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_bloqueos', 'Puede ver el dashboard: Bloqueos'), ('ver_oportunidades', 'Puede ver el dashboard: Oportunidades'), ('ver_desayunos', 'Puede ver el dashboard: Desayunos'), ('ver_tendencias', 'Puede ver el dashboard: Tendencias'), ('ver_alertas', 'Puede ver el dashboard: Alertas'), ('ver_ajustes', 'Puede ver el dashboard: Ajustes')]},
        ),
    ]
