# Generated by Django 5.2.17 on 2026-08-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dashboardaccess_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_bloqueos', 'Puede ver el dashboard: Bloqueos'), ('ver_desayunos', 'Puede ver el dashboard: Desayunos')]},
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dashboard', 'clave'), name='unico_ajuste_por_dashboard')],
            },
        ),
    ]
