# Generated by Django 5.2.17 on 2026-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dashboardaccess_options_dashboardsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoDesayunoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_code', models.CharField(max_length=20)),
                ('mes', models.DateField(help_text='Día 1 del mes presupuestado')),
                ('ingresos', models.FloatField(default=0.0)),
                ('gastos', models.FloatField(default=0.0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presupuesto de desayuno (mensual)',
                'verbose_name_plural': 'Presupuestos de desayuno (mensuales)',
                'constraints': [models.UniqueConstraint(fields=('property_code', 'mes'), name='unico_presupuesto_fb_por_hotel_mes')],
            },
        ),
    ]
