# Generated by Django 5.2.17 on 2026-09-04 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_presupuestodesayunomensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dashboardsetting',
            name='unico_ajuste_por_dashboard',
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='hotel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='dashboardsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('hotel_id__isnull', True)), fields=('dashboard', 'clave'), name='unico_ajuste_global_por_dashboard'),
        ),
        migrations.AddConstraint(
            model_name='dashboardsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('hotel_id__isnull', False)), fields=('dashboard', 'clave', 'hotel_id'), name='unico_ajuste_por_dashboard_y_hotel'),
        ),
    ]
